package com.learn.javacc.simple.simple1;/* Generated By:JavaCC: Do not edit this line. com.learn.javacc.simple.simple1.Simple1Constants.java */

/**
 * com.learn.javacc.simple.simple1.Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Simple1Constants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
